language: cpp
dist: trusty
sudo: required
cache: ccache
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "${MATRIX_EVAL}"; fi
- PATH=$PATH:$HOME/bin
- ${CXX} --version
install: travis/install_deps.sh
script: travis/compile.sh
env:
  global:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  matrix:
    - PLATFORM="native_static"
    - PLATFORM="native_dyn"
    - PLATFORM="win32_static"
    - PLATFORM="win32_dyn"
    - PLATFORM="android_arm"
    - PLATFORM="android_arm64"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - python3-pip
      - cmake
      - libbz2-dev
      - ccache
      - zlib1g-dev
      - uuid-dev
      - cython3
      - g++-mingw-w64-i686
      - gcc-mingw-w64-i686
      - gcc-mingw-w64-base
      - mingw-w64-tools

matrix:
  include:
    - env: PLATFORM="native_dyn"
      os: osx
