name: Packages

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-deb:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian-unstable
          - debian-bullseye
          - ubuntu-jammy
          - ubuntu-focal
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # Determine which PPA we should upload to
      - name: PPA
        id: ppa
        run: |
          if [[ $REF == refs/tags* ]]
          then
            echo "::set-output name=ppa::kiwixteam/release"
          else
            echo "::set-output name=ppa::kiwixteam/dev"
          fi
        env:
          REF: ${{ github.ref }}

      - uses: legoktm/gh-action-auto-dch@18025761b70898aac9ddb5bdc726bcd083926714 # master
        with:
          fullname: Kiwix builder
          email: release+launchpad@kiwix.org
          distro: ${{ matrix.distro }}

      - uses: legoktm/gh-action-build-deb@4f3fbf87de8bf0870f44624693cae17b7ad34ca2 # debian-unstable
        if: matrix.distro == 'debian-unstable'
        name: Build package for debian-unstable
        id: build-debian-unstable
        with:
          args: --no-sign

      - uses: legoktm/gh-action-build-deb@1f7501377e7c229f373748af433e5c3818eeae6e # debian-bullseye
        if: matrix.distro == 'debian-bullseye'
        name: Build package for debian-bullseye
        id: build-debian-bullseye
        with:
          args: --no-sign

      - uses: legoktm/gh-action-build-deb@56d1c4bc50f5525fa9b66ac6d7a984ece0428d46 # ubuntu-jammy
        if: matrix.distro == 'ubuntu-jammy'
        name: Build package for ubuntu-jammy
        id: build-ubuntu-jammy
        with:
          args: --no-sign
          ppa: ${{ steps.ppa.outputs.ppa }}

      - uses: legoktm/gh-action-build-deb@e58c0b09a3955e39a4ab83ffe03025d622dda039 # ubuntu-focal
        if: matrix.distro == 'ubuntu-focal'
        name: Build package for ubuntu-focal
        id: build-ubuntu-focal
        with:
          args: --no-sign
          ppa: ${{ steps.ppa.outputs.ppa }}

      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: Packages for ${{ matrix.distro }}
          path: output

      - uses: legoktm/gh-action-dput@a41ede69b89b473fb9de31db5f82aef098ca6492 # master
        name: Upload dev package
        # Only upload on pushes to main
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main' && startswith(matrix.distro, 'ubuntu-')
        with:
          gpg_key: ${{ secrets.LAUNCHPAD_GPG }}
          repository: ppa:kiwixteam/dev
          packages: output/*_source.changes

      - uses: legoktm/gh-action-dput@a41ede69b89b473fb9de31db5f82aef098ca6492 # master
        name: Upload release package
        if: github.event_name == 'release' && startswith(matrix.distro, 'ubuntu-')
        with:
          gpg_key: ${{ secrets.LAUNCHPAD_GPG }}
          repository: ppa:kiwixteam/release
          packages: output/*_source.changes
